-- SECCION 1: ROL, MUNICIPIO, TIPO_ALOJAMIENTO

CREATE TABLE rol (
  id_rol       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre       VARCHAR2(30)  NOT NULL,
  descripcion  VARCHAR2(200),
  CONSTRAINT pk_rol        PRIMARY KEY (id_rol),
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE municipio (
  id_municipio  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre        VARCHAR2(60) NOT NULL,
  CONSTRAINT pk_municipio        PRIMARY KEY (id_municipio),
  CONSTRAINT uq_municipio_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_alojamiento (
  id_tipo_alojamiento  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre               VARCHAR2(40)  NOT NULL,
  descripcion          VARCHAR2(200),
  CONSTRAINT pk_tipo_alojamiento  PRIMARY KEY (id_tipo_alojamiento),
  CONSTRAINT uq_tipo_aloj_nombre  UNIQUE (nombre)
);

INSERT INTO rol (id_rol, nombre, descripcion)
VALUES (1, 'ADMINISTRADOR', 'Administra la plataforma; no pertenece a un alojamiento');
INSERT INTO rol (id_rol, nombre, descripcion)
VALUES (2, 'ENCARGADO', 'Gestiona habitaciones, tarifas y reservas de un alojamiento');
COMMIT;


-- SECCION 2: ALOJAMIENTO y HABITACION

CREATE TABLE alojamiento (
  id_alojamiento       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre_comercial     VARCHAR2(120) NOT NULL,
  direccion            VARCHAR2(160) NOT NULL,
  estrellas            NUMBER(1)     NOT NULL,   -- autoasignadas por el alojamiento
  telefono             VARCHAR2(20)  NOT NULL,
  correo               VARCHAR2(120) NOT NULL,
  id_municipio         NUMBER        NOT NULL,
  id_tipo_alojamiento  NUMBER        NOT NULL,
  CONSTRAINT pk_alojamiento        PRIMARY KEY (id_alojamiento),
  CONSTRAINT uq_alojamiento_nombre UNIQUE (nombre_comercial),
  CONSTRAINT ck_alojamiento_estrellas CHECK (estrellas BETWEEN 1 AND 5),
  CONSTRAINT ck_alojamiento_correo    CHECK (correo LIKE '%_@_%._%'),
  CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio)
             REFERENCES municipio (id_municipio),
  CONSTRAINT fk_alojamiento_tipo      FOREIGN KEY (id_tipo_alojamiento)
             REFERENCES tipo_alojamiento (id_tipo_alojamiento)
);

CREATE TABLE habitacion (
  id_habitacion   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_alojamiento  NUMBER        NOT NULL,
  numero          VARCHAR2(10)  NOT NULL,
  capacidad       NUMBER(2)     NOT NULL,      
  tipo            VARCHAR2(10)  NOT NULL,
  descripcion     VARCHAR2(300),
  CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),
  CONSTRAINT uq_habitacion_numero UNIQUE (id_alojamiento, numero),
  CONSTRAINT uq_habitacion_aloj   UNIQUE (id_habitacion, id_alojamiento),
  CONSTRAINT ck_habitacion_capacidad CHECK (capacidad > 0),
  CONSTRAINT ck_habitacion_tipo CHECK (tipo IN ('SENCILLA','DOBLE','SUITE','CABANA')),
  CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento)
);


-- SECCION 3: Temporadas y tarifas

CREATE TABLE temporada (
  id_temporada  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre        VARCHAR2(80) NOT NULL,           
  nivel         VARCHAR2(5)  NOT NULL,
  fecha_inicio  DATE         NOT NULL,
  fecha_fin     DATE         NOT NULL,         
  CONSTRAINT pk_temporada        PRIMARY KEY (id_temporada),
  CONSTRAINT uq_temporada_nombre UNIQUE (nombre),
  CONSTRAINT ck_temporada_nivel  CHECK (nivel IN ('ALTA','MEDIA','BAJA')),
  CONSTRAINT ck_temporada_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE tarifa (
  id_tarifa      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_habitacion  NUMBER        NOT NULL,
  id_temporada   NUMBER        NOT NULL,
  valor_noche    NUMBER(10,2)  NOT NULL,
  CONSTRAINT pk_tarifa PRIMARY KEY (id_tarifa),
  CONSTRAINT uq_tarifa_hab_temp UNIQUE (id_habitacion, id_temporada),
  CONSTRAINT ck_tarifa_valor CHECK (valor_noche > 0),
  CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion)
             REFERENCES habitacion (id_habitacion),
  CONSTRAINT fk_tarifa_temporada  FOREIGN KEY (id_temporada)
             REFERENCES temporada (id_temporada)
);


-- SECCION 4: Clientes y reservas

CREATE TABLE cliente (
  id_cliente      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre          VARCHAR2(120) NOT NULL,
  documento       VARCHAR2(20)  NOT NULL,
  correo          VARCHAR2(120) NOT NULL,
  telefono        VARCHAR2(20)  NOT NULL,
  ciudad_origen   VARCHAR2(60)  NOT NULL,
  CONSTRAINT pk_cliente           PRIMARY KEY (id_cliente),
  CONSTRAINT uq_cliente_documento UNIQUE (documento),
  CONSTRAINT uq_cliente_correo    UNIQUE (correo),
  CONSTRAINT ck_cliente_correo    CHECK (correo LIKE '%_@_%._%')
);

CREATE TABLE reserva (
  id_reserva      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_cliente      NUMBER       NOT NULL,
  id_alojamiento  NUMBER       NOT NULL,
  fecha_reserva   DATE         NOT NULL,         
  check_in        DATE         NOT NULL,
  check_out       DATE         NOT NULL,
  estado          VARCHAR2(10) NOT NULL,
  fecha_cancelacion DATE,                    
  CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
  CONSTRAINT uq_reserva_aloj   UNIQUE (id_reserva, id_alojamiento),
  CONSTRAINT uq_reserva_estado UNIQUE (id_reserva, estado),
  CONSTRAINT ck_reserva_estado CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
  CONSTRAINT ck_reserva_fechas CHECK (check_out > check_in),
  CONSTRAINT ck_reserva_anticipo CHECK (fecha_reserva <= check_in),
  CONSTRAINT ck_reserva_cancelacion CHECK (
    (estado = 'CANCELADA' AND fecha_cancelacion IS NOT NULL)
    OR (estado <> 'CANCELADA' AND fecha_cancelacion IS NULL)),
  CONSTRAINT ck_reserva_fecha_cancel CHECK (
    fecha_cancelacion IS NULL
    OR (fecha_cancelacion >= fecha_reserva AND fecha_cancelacion <= check_in)),
  CONSTRAINT fk_reserva_cliente    FOREIGN KEY (id_cliente)
             REFERENCES cliente (id_cliente),
  CONSTRAINT fk_reserva_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento)
);

-- DECISION DE DISEÑO 1: una linea por habitacion reservada
CREATE TABLE reserva_habitacion (
  id_reserva_habitacion  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva             NUMBER        NOT NULL,
  id_habitacion          NUMBER        NOT NULL,
  id_alojamiento         NUMBER        NOT NULL,
  check_in               DATE          NOT NULL, 
  check_out              DATE          NOT NULL,
  huespedes              NUMBER(2)     NOT NULL,
  valor_estadia          NUMBER(12,2)  NOT NULL, 
  CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva_habitacion),
  CONSTRAINT uq_resha_reserva_hab  UNIQUE (id_reserva, id_habitacion),
  CONSTRAINT ck_resha_fechas    CHECK (check_out > check_in),
  CONSTRAINT ck_resha_huespedes CHECK (huespedes > 0),
  CONSTRAINT ck_resha_valor     CHECK (valor_estadia >= 0),
  CONSTRAINT fk_resha_reserva FOREIGN KEY (id_reserva, id_alojamiento)
             REFERENCES reserva (id_reserva, id_alojamiento),
  CONSTRAINT fk_resha_habitacion FOREIGN KEY (id_habitacion, id_alojamiento)
             REFERENCES habitacion (id_habitacion, id_alojamiento)
);


-- SECCION 5: Pagos

CREATE TABLE pago (
  id_pago     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva  NUMBER        NOT NULL,
  fecha_pago  DATE          NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  metodo      VARCHAR2(20)  NOT NULL,
  estado      VARCHAR2(12)  NOT NULL,
  CONSTRAINT pk_pago PRIMARY KEY (id_pago),
  CONSTRAINT ck_pago_monto  CHECK (monto > 0),
  CONSTRAINT ck_pago_metodo CHECK (metodo IN ('TARJETA_CREDITO','TARJETA_DEBITO',
                                              'PSE','TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
  CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva)
             REFERENCES reserva (id_reserva)
);


-- SECCION 6: Servicios complementarios

CREATE TABLE servicio (
  id_servicio     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_alojamiento  NUMBER        NOT NULL,
  nombre          VARCHAR2(80)  NOT NULL,
  descripcion     VARCHAR2(300),
  precio          NUMBER(10,2)  NOT NULL,
  CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
  CONSTRAINT uq_servicio_nombre UNIQUE (id_alojamiento, nombre),
  CONSTRAINT uq_servicio_aloj   UNIQUE (id_servicio, id_alojamiento),
  CONSTRAINT ck_servicio_precio CHECK (precio >= 0),
  CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento)
);

CREATE TABLE reserva_servicio (
  id_reserva_servicio  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva           NUMBER        NOT NULL,
  id_servicio          NUMBER        NOT NULL,
  id_alojamiento       NUMBER        NOT NULL,
  cantidad             NUMBER(3)     NOT NULL,
  precio_unitario      NUMBER(10,2)  NOT NULL,  
  CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),
  CONSTRAINT uq_resser_reserva_serv UNIQUE (id_reserva, id_servicio),
  CONSTRAINT ck_resser_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_resser_precio   CHECK (precio_unitario >= 0),
  CONSTRAINT fk_resser_reserva FOREIGN KEY (id_reserva, id_alojamiento)
             REFERENCES reserva (id_reserva, id_alojamiento),
  CONSTRAINT fk_resser_servicio FOREIGN KEY (id_servicio, id_alojamiento)
             REFERENCES servicio (id_servicio, id_alojamiento)
);


-- SECCION 7: Reseñas

CREATE TABLE resena (
  id_resena       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva      NUMBER        NOT NULL,
  estado_reserva  VARCHAR2(10)  DEFAULT 'COMPLETADA' NOT NULL,
  calificacion    NUMBER(1)     NOT NULL,
  comentario      VARCHAR2(500),               
  fecha_resena    DATE          NOT NULL,
  CONSTRAINT pk_resena PRIMARY KEY (id_resena),
  CONSTRAINT uq_resena_reserva UNIQUE (id_reserva),   
  CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5),
  CONSTRAINT ck_resena_estado CHECK (estado_reserva = 'COMPLETADA'),
  CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva, estado_reserva)
             REFERENCES reserva (id_reserva, estado)
);


-- SECCION 8: Usuarios internos

CREATE TABLE usuario_sistema (
  id_usuario      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username        VARCHAR2(30)  NOT NULL,
  nombre          VARCHAR2(120) NOT NULL,
  correo          VARCHAR2(120) NOT NULL,
  id_rol          NUMBER        NOT NULL,
  id_alojamiento  NUMBER,                    
  activo          CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_usuario_sistema PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuario_username UNIQUE (username),
  CONSTRAINT ck_usuario_activo CHECK (activo IN ('S','N')),
  CONSTRAINT ck_usuario_correo CHECK (correo LIKE '%_@_%._%'),
  CONSTRAINT ck_usuario_rol_aloj CHECK (
    (id_rol = 1 AND id_alojamiento IS NULL)
    OR (id_rol = 2 AND id_alojamiento IS NOT NULL)),
  CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
             REFERENCES rol (id_rol),
  CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento)
);


-- SECCION 9: Comentarios del diccionario de datos

COMMENT ON TABLE rol IS 'Catálogo de roles de los usuarios internos (administrador, encargado).';
COMMENT ON TABLE municipio IS 'Los 12 municipios del Quindío donde se ubica la oferta de alojamiento.';
COMMENT ON TABLE tipo_alojamiento IS 'Catálogo de tipos: finca cafetera, hotel, glamping, hostal y otros.';
COMMENT ON TABLE alojamiento IS 'Establecimiento turístico de un municipio y un tipo; las estrellas las autoasigna el propio alojamiento.';
COMMENT ON TABLE habitacion IS 'Habitación de un alojamiento con número único dentro de él, capacidad máxima de huéspedes y tipo.';
COMMENT ON TABLE temporada IS 'Rango de fechas por año con nivel ALTA, MEDIA o BAJA; los rangos no se solapan y cubren todos los días del periodo.';
COMMENT ON TABLE tarifa IS 'Valor por noche de una habitación en una temporada; una fila por cada cruce habitación x temporada.';
COMMENT ON TABLE cliente IS 'Persona que reserva; documento y correo son únicos; la ciudad de origen puede estar fuera del Quindío.';
COMMENT ON TABLE reserva IS 'Cabecera de la reserva: cliente, alojamiento, rango general de fechas y estado.';
COMMENT ON TABLE reserva_habitacion IS 'Línea de reserva por habitación, con fechas propias dentro del rango general y valor de la estadía calculado noche a noche.';
COMMENT ON TABLE pago IS 'Abono o pago total de una reserva; una reserva puede tener varios pagos.';
COMMENT ON TABLE servicio IS 'Servicio complementario que pertenece a un alojamiento específico.';
COMMENT ON TABLE reserva_servicio IS 'Servicios contratados en una reserva, con cantidad y precio unitario congelado.';
COMMENT ON TABLE resena IS 'Reseña de una reserva completada: calificación de 1 a 5 y comentario opcional.';
COMMENT ON TABLE usuario_sistema IS 'Usuario interno de la plataforma: administrador o encargado de un alojamiento.';

COMMENT ON COLUMN alojamiento.estrellas IS 'Calificación en estrellas (1 a 5) autoasignada por el alojamiento.';
COMMENT ON COLUMN temporada.fecha_fin IS 'Último día incluido en la temporada.';
COMMENT ON COLUMN reserva.estado IS 'PENDIENTE, CONFIRMADA, CANCELADA o COMPLETADA.';
COMMENT ON COLUMN reserva.fecha_cancelacion IS 'Solo para reservas CANCELADAS. Reembolso: más de 5 días entre la cancelación y el check-in devuelve el 80 %; con 5 días o menos no hay reembolso.';
COMMENT ON COLUMN reserva_habitacion.valor_estadia IS 'Valor pactado de la estadía: suma de la tarifa vigente cada noche; se congela al reservar.';
COMMENT ON COLUMN reserva_servicio.precio_unitario IS 'Precio del servicio al momento de contratarlo.';
COMMENT ON COLUMN pago.estado IS 'EXITOSO, FALLIDO, PENDIENTE o REEMBOLSADO; solo los exitosos cuentan para considerar la reserva pagada.';
COMMENT ON COLUMN resena.estado_reserva IS 'Siempre COMPLETADA; junto con id_reserva impide reseñar reservas que no se hospedaron.';
COMMENT ON COLUMN usuario_sistema.id_alojamiento IS 'Alojamiento que gestiona el encargado; nulo para administradores de la plataforma.';


-- SECCION 10: Verificacion

-- deben aparecer 15 tablas
SELECT COUNT(*) AS total_tablas FROM user_tables;

-- deben aparecer las restricciones PK = 15, FK = 16, UNIQUE = 18 y CK_ = 27
SELECT DECODE(constraint_type, 'P', 'PK', 'R', 'FK', 'U', 'UNIQUE',
              'C', 'CHECK y NOT NULL', constraint_type) AS tipo,
       COUNT(*) AS cantidad
  FROM user_constraints
 GROUP BY constraint_type
 ORDER BY constraint_type;

-- deben aparecer los 2 roles de catalogo
SELECT id_rol, nombre FROM rol ORDER BY id_rol;

-- Catalogo rol ADMINISTRADOR Y ENCARGADO
SELECT id_rol, nombre FROM rol ORDER BY id_rol;

-- columna de cancelacion reserva
SELECT table_name, column_name
  FROM user_tab_columns
 WHERE table_name = 'RESERVA' AND column_name = 'FECHA_CANCELACION';
 
-- comentarios 15
SELECT COUNT(*) AS tablas_con_comentario
  FROM user_tab_comments
 WHERE comments IS NOT NULL
   AND table_name IN (SELECT table_name FROM user_tables);
